### ISSUE TITLE
Incomplete SSL certificate chain

### ISSUE THREAD

**Issue by ticky** [museumsvictoria/collections-online#16]
Hi there, I wasn’t sure where to send a technical issue like this, but, I’m having some problems with the API stemming from the way your server is configured.

Your server is returning _your site's_ SSL certificate, but not GoDaddy’s intermediate certificate, which means it works okay on desktop systems which have clever storage of intermediate certificates they’ve seen on the web, but on server-type systems presents a problem as the intermediate certificate is intended to be sent as part of the certificate chain so your certificate can be verified to be trusted against the root certificates.

You can take a look at the SSL Labs report yourself: https://www.ssllabs.com/ssltest/analyze.html?d=collections.museumvictoria.com.au

The pertinent part is here:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/282113/82614298-56a31600-9b7c-11ea-8b3e-6d85a0caafa5.png">

It looks like your server requires some reconfiguration to include the intermediate certificate (that “Go Daddy Secure Certificate Authority - G2” one), as described in GoDaddy’s documentation: https://ca.godaddy.com/help/what-is-an-intermediate-certificate-868

**Comment by michael-mason** [comment]
Oh hey thanks for the heads up will forward this on to the server admin : )

**Comment by michael-mason** [comment]
Ok apparently they are all over this issue and will be sorting it out soon....

**Comment by michael-mason** [comment]
Sorry bout the wait, but we have moved the site from our old domain to the new one that has the correctly managed certs.  Old domain is still there but you should now get a 301 redirect to the new url which is now...

https://collections.museumsvictoria.com.au/

**Comment by ticky** [comment]
A 301 won’t do anything if the old domain still can’t be connected to, unfortunately!

**Comment by ticky** [comment]
The new domain does, in fact, include the necessary intermediate certificate. I’ll update my code to specify the new domain! Thanks for looking into this. ☺️
