### ISSUE TITLE
acorn proton information is wrong

### ISSUE THREAD

**Issue by grokitall** [museumsvictoria/collections-online#50]
i was around when the first rumours of the proton came out. it was a dual 6502 design with the first core acting as a front end, handling all of the io, and the second core being headless offering a large memory for the time, communication over a dedicated io bus between the two.

when the bbc micro initiative asked for designs, acorn realised that this proton design was a good fit, exceeding the requirements, with two problems, it was too expensive, and it would not be ready on time. they solved this by extracting the front end design, but keeping the tube second processor bus, so they could add the 6502 second processor later, which they did as an add on unit.

this had the unexpected advantage that they could later add other processors by leveraging the strength of the design.

the initial design for what became the model A did not include a number of pieces of hardware as standard, while having the circuitry on the motherboard. missing hardware included the speech synthesiser, the floppy disk interface, and a significant amount of the initial ram design.

**Comment by michael-mason** [comment]
Heya grokitall, I assume you're talking about this object? https://collections.museumsvictoria.com.au/items/396845 

if it is, I will try and get it to the relevant people to correct on the website :)

**Comment by grokitall** [comment]
that is the one.

i am not aware specifically of something sold as a bbc proton, but the
acorn proton was designed to be the successor of the acorn atom.

when the bbc decided to create a computer, and put out a call for
proposals, the people at acorn realised that they already had an unbuilt
design which massively exceeded the specs.

this was then cut down to fit with the specs in a way which could be
implemented fast (under a week), while still allowing the original design
to be constructed as a super set of the design they submitted.

as an interesting side point, sinclair lost out because they were well
known for pushing the tech just that little bit too far, making their
previous devices too unreliable.

this definitely looks like the right article, but the device shown looks
like a standard bbc micro case. without seeing a visual of the pcb, i could
not even guess which version.

at a time when the competition was the commodore pet, and the 1k zx81, the
original design for the proton called for 2 6502 processors, the second
containing 64k of ram. it also had lots of completely unique io
capabilities, most of which were on the model a circuit board, but had not
had the driver software written due to time constraints.

**Comment by michael-mason** [comment]
Thanks for the fascinating information :)

I've passed this on to our public enquiries team who should be in touch shortly.  If its ok with you I will close this as an issue as the public enquiry system is probably a better place to converse.

Thanks again!

**Comment by grokitall** [comment]
fine, i only contacted you this way as it seemed all the data for the
webpages was in the repo, and i could not find any other method of contact.
