### ISSUE TITLE
Random sort appears to be fixed

### ISSUE THREAD

**Issue by ticky** [museumsvictoria/collections-online#7]
I finally got around to trying out the random sort behaviour mentioned in #6, and it appears that the result may be cached, or the randomness otherwise isn’t so random.

Requesting `https://collections.museumvictoria.com.au/api/items?perpage=1&sort=random` seems to consistently return [item 58742, "Medal - Jacques Delille, France, 1821”](https://collections.museumvictoria.com.au/items/58742)!

I’ve verified this behaviour on multiple systems and with clean caches. Jacques is just _so_ random! 😜

**Comment by mistydemeo** [comment]
![random_number](https://cloud.githubusercontent.com/assets/780485/24754741/06015aca-1b1b-11e7-9ecf-27893737e19d.png)

**Comment by michael-mason** [comment]
whoops yes I am indeed aggressively caching the results... might wanna turn that off for random sort requests -_-

**Comment by ticky** [comment]
Thanks! Thanks to the changes in #6, I was able to [request just one item per tweet](https://github.com/ticky/museum-things/commit/700cb71cf334606778d39d8b4c75b48f2e5d21e1), but this will let me make just one request, rather than two! 😃

**Comment by michael-mason** [comment]
Well I probably should have picked this up but that endpoint is the wrong one to call if you want to apply any sorting which is maybe a separate issue that needs addressing.  At the moment the search endpoint is the only one that will allow sorting, so maybe try this url.

[https://collections.museumvictoria.com.au/api/search?recordtype=item&perpage=1&sort=random](url)

As the results are random each time it shouldn't be caching it either.

**Comment by ticky** [comment]
Aha! Perfect 😃

**Comment by ticky** [comment]
Following up: this worked! 😄
